version: "3.8"
networks:
  cassandra:
services:
  cassandra01:
    image: cassandra:4.0
    container_name: cassandra01
    hostname: cassandra01
    # mem_limit: 2g
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - D:\_WS_Developpement\tweets_analysis\cassandra\cassandra_data01:/var/lib/cassandra
      # - ./etc/cassandra01:/etc/cassandra
    environment: &environment # Déclaration des variables d'environnement
      CASSANDRA_SEEDS: "cassandra01,cassandra02"
      CASSANDRA_CLUSTER_NAME: YnovJordy

  cassandra02:
    image: cassandra:4.0
    container_name: cassandra02
    hostname: cassandra02
    # mem_limit: 2g
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9043:9042"
    volumes:
      - D:\_WS_Developpement\tweets_analysis\cassandra\cassandra_data02:/var/lib/cassandra
      # - ./etc/cassandra02:/etc/cassandra
    environment: *environment # on pointe sur les mêmes variables d'environnement
    depends_on:
      cassandra01:
        condition: service_healthy

  cassandra03:
    image: cassandra:4.0
    container_name: cassandra03
    hostname: cassandra03
    # mem_limit: 2g
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9044:9042"
    volumes:
      - D:\_WS_Developpement\tweets_analysis\cassandra\cassandra_data03:/var/lib/cassandra
    environment: *environment
    depends_on:
      cassandra02:
        condition: service_healthy

  cassandra04:
    image: cassandra:4.0
    container_name: cassandra04
    hostname: cassandra04
    # mem_limit: 2g
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9045:9042"
    volumes:
      - D:\_WS_Developpement\tweets_analysis\cassandra\cassandra_data04:/var/lib/cassandra
    environment: *environment
    depends_on:
      cassandra02:
        condition: service_healthy
